"""FL-XGB-Thesis: Thesis S2 — Network Intrusion Detection via Federated Learning."""

from .config import (
    BASE_DIR, DATA_DIR, RESULTS_DIR, LOGS_DIR,
    TRAIN_CSV, VAL_CSV, TEST_CSV,
    NUM_CLIENTS, FL_ROUNDS, LOCAL_EPOCHS, FRACTION_FIT,
    DIRICHLET_ALPHA,
    XGB_PARAMS, LGB_PARAMS, CNN_PARAMS,
    SEED, GPU_DEVICE, CPU_THREADS,
    TRAIN_SUBSAMPLE_RATIO, LOW_MEM_MODE,
)

__all__ = [
    "BASE_DIR", "DATA_DIR", "RESULTS_DIR", "LOGS_DIR",
    "TRAIN_CSV", "VAL_CSV", "TEST_CSV",
    "NUM_CLIENTS", "FL_ROUNDS", "LOCAL_EPOCHS", "FRACTION_FIT",
    "DIRICHLET_ALPHA",
    "XGB_PARAMS", "LGB_PARAMS", "CNN_PARAMS",
    "SEED", "GPU_DEVICE", "CPU_THREADS",
    "TRAIN_SUBSAMPLE_RATIO", "LOW_MEM_MODE",
]
